### ISSUE TITLE
script database

### ISSUE THREAD

**Issue by ayoubAnbara** [Ayoub-Tasnaoui/produit_categorie#1]
hi,
can you share with us script to create database

**Comment by bobo93-crypto** [comment]
hi,
this is the script of my creation of DataBase by mysql : 

CREATE DATABASE IF NOT EXISTS `bdprojet` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `bdprojet`;

-- Listage de la structure de la table bdprojet. categorie
CREATE TABLE IF NOT EXISTS `categorie` (
  `id` int(11) NOT NULL,
  `nom` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Les données exportées n'étaient pas sélectionnées.

-- Listage de la structure de la table bdprojet. produit
CREATE TABLE IF NOT EXISTS `produit` (
  `id` int(11) NOT NULL,
  `nom` varchar(50) NOT NULL DEFAULT '',
  `pu` decimal(10,0) NOT NULL DEFAULT '0',
  `qte` int(11) NOT NULL,
  `Id_Cat` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_produit_categorie` (`Id_Cat`),
  CONSTRAINT `FK_produit_categorie` FOREIGN KEY (`Id_Cat`) REFERENCES `categorie` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
